### ISSUE TITLE
Started the rom but normal graphics from original 

### ISSUE THREAD

**Issue by FNCCorruption** [Rosalie241/BetterMajorasMaskInstaller#10]
Hey in which folder i need to put the rom in? I put the rom in cache and when i started the rom it was actually the normal game.

**Comment by Rosalie241** [comment]
1) the ROM can be placed anywhere on your computer, it's irrelevant 
2) can you take a screenshot of settings -> configure graphics plugin -> texture enhancement
3) can you take a screenshot of the `Plugin\GFX\cache` folder?(if you didn't change the install location, that should be in `%localappdata%\Project64`)

**Comment by FNCCorruption** [comment]
Hey here are the screenshots 
<img width="1152" alt="MMHD" src="https://user-images.githubusercontent.com/68546264/87965184-a427fa80-cabb-11ea-8d1a-51734b26a16e.png">
<img width="1152" alt="MMHD2" src="https://user-images.githubusercontent.com/68546264/87965192-a722eb00-cabb-11ea-8315-4a6899ad24fd.png">

**Comment by Rosalie241** [comment]
it should be functional then, can you take a screenshot when you're in-game?

**Comment by FNCCorruption** [comment]
Hey i reinstalled the programm now its actually functional. Is it normal that the intro cutscene doesn´t use the hd graphics and I don´t no why but its loading texture pack in less than 5 seconds, i hope it loaded everything. 
Thanks for help

**Comment by Rosalie241** [comment]
> 
> 
> Hey i reinstalled the programm now its actually functional. Is it normal that the intro cutscene doesn´t use the hd graphics and I don´t no why but its loading texture pack in less than 5 seconds, i hope it loaded everything.
> Thanks for help

that intro issue sounds odd, I have no idea.
regarding the fast loading, Nerrel switched to the HTS format (as opposed to the HTC format), which only loads textures when they're required, this is needed because project64 is 32bit, which means it can only use upto 4 GB of memory (with LAA), previously, when using the HTC pack, it'd take 1) a long time to load and 2) it'd crash project64 due to reaching the 32bit memory limits so HTS is a solution (for now).

anyways, hope you enjoy the game :heart:
